spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 설정
    show-sql: true # SQL 쿼리 로그 출력
logging:
  level:
    org.springframework: debug
server:
  port: 8088